import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext();

const english = {
  welcomeBack: "Welcome back",
  welcomeTo: "Sign in to continue to your escrow dashboard.",
  username: "Username",
  password: "Password",
  signIn: "Sign in",
  signOut: "Sign out",
  registerPrompt: "Don't have an account yet? Register now.",
  signUp: "Sign up",
  haveAccount: "Already have an account?",
  name: "Name",
  registerSubtitle: "Create your account and start using escrow services.",
  registerError: "Registration failed. Please try again.",
  language: "Language",
  verifyTitle: "Verify your account",
  verifySubtitle: "Enter the code sent to your email to finish signing in.",
  verifyCode: "Verification code",
  verifySubmit: "Verify",
  verifySent: "A code was sent to",
  resendCode: "Resend code",
  verifySuccess: "Verification complete. You can now use the app.",
  verifyError: "Verification failed. Check your code and try again.",
  backToLogin: "Back to login",
  linkLoginTitle: "Sign in with a short link",
  linkLoginSubtitle: "We are validating your secure access code.",
  linkLoginPending: "Verifying short link...",
  loginLinkSuccess: "You are signed in with your short link.",
  loginLinkError: "Unable to verify the short link.",
  invalidLink: "Invalid or missing link code.",
  notSignedIn: "You are not signed in.",
  signInRequired: "Sign in required",

  clientWorkspace: "Client workspace",
  dashboardWelcome: "Welcome, {name}",
  dashboardSubtitle: "Create escrow requests, respond to requests sent to you, message clients, and track only your own deals.",
  activeTransactions: "Active transactions",
  activeTransactionsHelp: "In progress right now",
  totalEscrowValue: "Total escrow value",
  totalEscrowValueHelp: "Your tracked volume",
  pendingAction: "Pending action",
  pendingActionHelp: "Funding or release steps",
  nextStep: "Next step",
  nextStepHelp: "Most urgent transaction",
  noActionNeeded: "No action needed",
  yourTransactions: "Your Transactions",
  escrowRecordsCount: "{shown} of {total} escrow records",
  refresh: "Refresh",
  refreshing: "Refreshing",
  loadingTransactions: "Loading transactions...",
  noTransactionsStatus: "No transactions match this status.",
  buyer: "Buyer",
  seller: "Seller",
  amount: "Amount",
  due: "Due",
  accept: "Accept",
  deny: "Deny",
  requestPendingCanRespond: "This request is pending. You can accept or deny it.",
  requestPendingWaiting: "Waiting for the receiving client to accept or deny this request.",
  requestDenied: "This request was denied.",
  transactionCompleted: "This transaction is completed.",
  requestActionUnavailable: "Accept or deny is only available while a request is pending acceptance.",
  newTransaction: "New Transaction",
  newTransactionHelp: "Send an escrow request to another client for approval.",
  receivingClient: "Receiving client",
  selectClient: "Select a client",
  receivingClientPlaceholder: "Type client name or username",
  itemOrService: "Item or service",
  itemPlaceholder: "What is being protected?",
  dueDate: "Due date",
  createTransaction: "Create transaction",
  creating: "Creating...",
  transactionRequestSent: "Transaction request sent to the receiving client.",
  unableCreateTransaction: "Unable to create transaction.",
  transactionAccepted: "Transaction accepted.",
  transactionDenied: "Transaction denied.",
  unableUpdateTransaction: "Unable to update transaction.",
  inviteClient: "Invite a client",
  inviteClientHelp: "Create a registration link they can use to join and message you.",
  createInviteLink: "Create invite link",
  creatingLink: "Creating link...",
  copy: "Copy",
  inviteCreated: "Invite link created.",
  inviteCopied: "Invite link copied.",
  inviteReady: "Invite link is ready to share.",
  unableInvite: "Unable to create invite link.",
  messages: "Messages",
  messagesHelp: "Send text and image updates to another client.",
  conversingWith: "You are conversing with {name}.",
  client: "Client",
  loadingMessages: "Loading messages...",
  noMessages: "No messages yet. Start the conversation below.",
  you: "You",
  message: "Message",
  writeMessage: "Write a message",
  image: "Image",
  removeImage: "Remove image",
  sendMessage: "Send message",
  sending: "Sending...",
  messageSent: "Message sent.",
  unableMessages: "Unable to load messages.",
  unableSendMessage: "Unable to send message.",
  attachImageFile: "Please attach an image file.",
  imageTooLarge: "Images must be 5 MB or smaller.",
  unableTransactions: "Unable to load your transactions.",
  unableContacts: "Unable to load client contacts.",
  statusAll: "All",
  statusPendingAcceptance: "Pending Acceptance",
  statusFundingPending: "Funding Pending",
  statusInReview: "In Review",
  statusAwaitingRelease: "Awaiting Release",
  statusDisputed: "Disputed",
  statusDenied: "Denied",
  statusCompleted: "Completed",
};

const translations = {
  English: english,
  Japanese: {
    welcomeBack: "\u304a\u304b\u3048\u308a\u306a\u3055\u3044",
    welcomeTo: "\u30a8\u30b9\u30af\u30ed\u30fc\u30c0\u30c3\u30b7\u30e5\u30dc\u30fc\u30c9\u306b\u9032\u3080\u306b\u306f\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002",
    username: "\u30e6\u30fc\u30b6\u30fc\u540d",
    password: "\u30d1\u30b9\u30ef\u30fc\u30c9",
    signIn: "\u30b5\u30a4\u30f3\u30a4\u30f3",
    signOut: "\u30b5\u30a4\u30f3\u30a2\u30a6\u30c8",
    signUp: "\u767b\u9332",
    language: "\u8a00\u8a9e",
    notSignedIn: "\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u3044\u307e\u305b\u3093\u3002",
    clientWorkspace: "\u30af\u30e9\u30a4\u30a2\u30f3\u30c8\u30ef\u30fc\u30af\u30b9\u30da\u30fc\u30b9",
    dashboardWelcome: "\u3088\u3046\u3053\u305d\u3001{name}",
    dashboardSubtitle: "\u30a8\u30b9\u30af\u30ed\u30fc\u4f9d\u983c\u3001\u627f\u8a8d\u3001\u30e1\u30c3\u30bb\u30fc\u30b8\u3001\u81ea\u5206\u306e\u53d6\u5f15\u3092\u7ba1\u7406\u3067\u304d\u307e\u3059\u3002",
    activeTransactions: "\u30a2\u30af\u30c6\u30a3\u30d6\u53d6\u5f15",
    totalEscrowValue: "\u30a8\u30b9\u30af\u30ed\u30fc\u5408\u8a08",
    pendingAction: "\u4fdd\u7559\u4e2d\u306e\u64cd\u4f5c",
    nextStep: "\u6b21\u306e\u30b9\u30c6\u30c3\u30d7",
    noActionNeeded: "\u64cd\u4f5c\u306f\u4e0d\u8981\u3067\u3059",
    yourTransactions: "\u3042\u306a\u305f\u306e\u53d6\u5f15",
    refresh: "\u66f4\u65b0",
    refreshing: "\u66f4\u65b0\u4e2d",
    buyer: "\u8cb7\u3044\u624b",
    seller: "\u58f2\u308a\u624b",
    amount: "\u91d1\u984d",
    due: "\u671f\u9650",
    accept: "\u627f\u8a8d",
    deny: "\u62d2\u5426",
    newTransaction: "\u65b0\u3057\u3044\u53d6\u5f15",
    receivingClient: "\u53d7\u4fe1\u30af\u30e9\u30a4\u30a2\u30f3\u30c8",
    selectClient: "\u30af\u30e9\u30a4\u30a2\u30f3\u30c8\u3092\u9078\u629e",
    receivingClientPlaceholder: "\u30af\u30e9\u30a4\u30a2\u30f3\u30c8\u540d\u307e\u305f\u306f\u30e6\u30fc\u30b6\u30fc\u540d",
    itemOrService: "\u5546\u54c1\u307e\u305f\u306f\u30b5\u30fc\u30d3\u30b9",
    dueDate: "\u671f\u65e5",
    createTransaction: "\u53d6\u5f15\u3092\u4f5c\u6210",
    messages: "\u30e1\u30c3\u30bb\u30fc\u30b8",
    conversingWith: "{name}\u3068\u4f1a\u8a71\u4e2d\u3067\u3059\u3002",
    client: "\u30af\u30e9\u30a4\u30a2\u30f3\u30c8",
    message: "\u30e1\u30c3\u30bb\u30fc\u30b8",
    image: "\u753b\u50cf",
    sendMessage: "\u9001\u4fe1",
    you: "\u3042\u306a\u305f",
    statusAll: "\u3059\u3079\u3066",
    statusPendingAcceptance: "\u627f\u8a8d\u5f85\u3061",
    statusFundingPending: "\u8cc7\u91d1\u5f85\u3061",
    statusInReview: "\u30ec\u30d3\u30e5\u30fc\u4e2d",
    statusAwaitingRelease: "\u89e3\u653e\u5f85\u3061",
    statusDisputed: "\u7d1b\u4e89",
    statusDenied: "\u62d2\u5426\u6e08\u307f",
    statusCompleted: "\u5b8c\u4e86",
  },
  French: {
    welcomeBack: "Bon retour",
    welcomeTo: "Connectez-vous pour acceder a votre tableau de bord escrow.",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    signIn: "Se connecter",
    signOut: "Se deconnecter",
    signUp: "S'inscrire",
    language: "Langue",
    notSignedIn: "Vous n'etes pas connecte.",
    clientWorkspace: "Espace client",
    dashboardWelcome: "Bienvenue, {name}",
    dashboardSubtitle: "Creez des demandes escrow, repondez aux demandes recues, envoyez des messages et suivez uniquement vos transactions.",
    activeTransactions: "Transactions actives",
    totalEscrowValue: "Valeur escrow totale",
    pendingAction: "Action en attente",
    nextStep: "Prochaine etape",
    noActionNeeded: "Aucune action requise",
    yourTransactions: "Vos transactions",
    refresh: "Actualiser",
    refreshing: "Actualisation",
    buyer: "Acheteur",
    seller: "Vendeur",
    amount: "Montant",
    due: "Echeance",
    accept: "Accepter",
    deny: "Refuser",
    newTransaction: "Nouvelle transaction",
    receivingClient: "Client destinataire",
    selectClient: "Selectionner un client",
    receivingClientPlaceholder: "Saisir le nom ou l'utilisateur du client",
    itemOrService: "Article ou service",
    dueDate: "Date limite",
    createTransaction: "Creer la transaction",
    messages: "Messages",
    conversingWith: "Vous conversez avec {name}.",
    client: "Client",
    message: "Message",
    image: "Image",
    sendMessage: "Envoyer",
    you: "Vous",
    statusAll: "Tous",
    statusPendingAcceptance: "Acceptation en attente",
    statusFundingPending: "Financement en attente",
    statusInReview: "En revue",
    statusAwaitingRelease: "Liberation en attente",
    statusDisputed: "Litige",
    statusDenied: "Refuse",
    statusCompleted: "Termine",
  },
  Spanish: {
    welcomeBack: "Bienvenido de nuevo",
    welcomeTo: "Inicia sesion para continuar a tu panel de escrow.",
    username: "Usuario",
    password: "Contrasena",
    signIn: "Iniciar sesion",
    signOut: "Cerrar sesion",
    signUp: "Registrarse",
    language: "Idioma",
    notSignedIn: "No has iniciado sesion.",
    clientWorkspace: "Espacio del cliente",
    dashboardWelcome: "Bienvenido, {name}",
    dashboardSubtitle: "Crea solicitudes de escrow, responde solicitudes recibidas, envia mensajes y revisa solo tus transacciones.",
    activeTransactions: "Transacciones activas",
    totalEscrowValue: "Valor total en escrow",
    pendingAction: "Accion pendiente",
    nextStep: "Siguiente paso",
    noActionNeeded: "No se requiere accion",
    yourTransactions: "Tus transacciones",
    refresh: "Actualizar",
    refreshing: "Actualizando",
    buyer: "Comprador",
    seller: "Vendedor",
    amount: "Monto",
    due: "Vence",
    accept: "Aceptar",
    deny: "Denegar",
    newTransaction: "Nueva transaccion",
    receivingClient: "Cliente receptor",
    selectClient: "Selecciona un cliente",
    receivingClientPlaceholder: "Escribe nombre o usuario del cliente",
    itemOrService: "Articulo o servicio",
    dueDate: "Fecha limite",
    createTransaction: "Crear transaccion",
    messages: "Mensajes",
    conversingWith: "Estas conversando con {name}.",
    client: "Cliente",
    message: "Mensaje",
    image: "Imagen",
    sendMessage: "Enviar",
    you: "Tu",
    statusAll: "Todo",
    statusPendingAcceptance: "Aceptacion pendiente",
    statusFundingPending: "Financiacion pendiente",
    statusInReview: "En revision",
    statusAwaitingRelease: "Esperando liberacion",
    statusDisputed: "En disputa",
    statusDenied: "Denegado",
    statusCompleted: "Completado",
  },
  Mandarin: {
    welcomeBack: "\u6b22\u8fce\u56de\u6765",
    welcomeTo: "\u8bf7\u767b\u5f55\u4ee5\u7ee7\u7eed\u4f7f\u7528\u6258\u7ba1\u4eea\u8868\u677f\u3002",
    username: "\u7528\u6237\u540d",
    password: "\u5bc6\u7801",
    signIn: "\u767b\u5f55",
    signOut: "\u9000\u51fa\u767b\u5f55",
    signUp: "\u6ce8\u518c",
    language: "\u8bed\u8a00",
    notSignedIn: "\u60a8\u5c1a\u672a\u767b\u5f55\u3002",
    clientWorkspace: "\u5ba2\u6237\u5de5\u4f5c\u53f0",
    dashboardWelcome: "\u6b22\u8fce\uff0c{name}",
    dashboardSubtitle: "\u521b\u5efa\u6258\u7ba1\u8bf7\u6c42\uff0c\u56de\u590d\u8bf7\u6c42\uff0c\u53d1\u9001\u6d88\u606f\uff0c\u5e76\u53ea\u8ddf\u8e2a\u81ea\u5df1\u7684\u4ea4\u6613\u3002",
    activeTransactions: "\u6d3b\u8dc3\u4ea4\u6613",
    totalEscrowValue: "\u6258\u7ba1\u603b\u989d",
    pendingAction: "\u5f85\u5904\u7406",
    nextStep: "\u4e0b\u4e00\u6b65",
    noActionNeeded: "\u65e0\u9700\u64cd\u4f5c",
    yourTransactions: "\u60a8\u7684\u4ea4\u6613",
    refresh: "\u5237\u65b0",
    refreshing: "\u5237\u65b0\u4e2d",
    buyer: "\u4e70\u65b9",
    seller: "\u5356\u65b9",
    amount: "\u91d1\u989d",
    due: "\u622a\u6b62",
    accept: "\u63a5\u53d7",
    deny: "\u62d2\u7edd",
    newTransaction: "\u65b0\u4ea4\u6613",
    receivingClient: "\u63a5\u6536\u5ba2\u6237",
    selectClient: "\u9009\u62e9\u5ba2\u6237",
    receivingClientPlaceholder: "\u8f93\u5165\u5ba2\u6237\u59d3\u540d\u6216\u7528\u6237\u540d",
    itemOrService: "\u5546\u54c1\u6216\u670d\u52a1",
    dueDate: "\u5230\u671f\u65e5",
    createTransaction: "\u521b\u5efa\u4ea4\u6613",
    messages: "\u6d88\u606f",
    conversingWith: "\u60a8\u6b63\u5728\u4e0e {name} \u5bf9\u8bdd\u3002",
    client: "\u5ba2\u6237",
    message: "\u6d88\u606f",
    image: "\u56fe\u7247",
    sendMessage: "\u53d1\u9001",
    you: "\u60a8",
    statusAll: "\u5168\u90e8",
    statusPendingAcceptance: "\u5f85\u63a5\u53d7",
    statusFundingPending: "\u5f85\u4ed8\u6b3e",
    statusInReview: "\u5ba1\u6838\u4e2d",
    statusAwaitingRelease: "\u7b49\u5f85\u91ca\u653e",
    statusDisputed: "\u4e89\u8bae",
    statusDenied: "\u5df2\u62d2\u7edd",
    statusCompleted: "\u5df2\u5b8c\u6210",
  },
};

const languageCodes = {
  English: "en",
  Japanese: "ja",
  French: "fr",
  Spanish: "es",
  Mandarin: "zh",
};

export const availableLanguages = Object.keys(translations);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem("language");
    return translations[stored] ? stored : "English";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = languageCodes[language] || "en";
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: {
        ...english,
        ...(translations[language] ?? {}),
      },
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
